-- DROP TABLE IF EXISTS cats_avatar;
-- DROP TABLE IF EXISTS cats;

CREATE TABLE IF NOT EXISTS cats
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR     NOT NULL,
    email      VARCHAR     NOT NULL UNIQUE,
    password   VARCHAR     NOT NULL,
    avatar     BYTEA       NOT NULL,
    rate_user  BIGINT,
    rate_world BIGINT,
    role       VARCHAR(10) NOT NULL,
    state      VARCHAR(10) NOT NULL,
    CONSTRAINT uq_email_cat UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS cats_avatar
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image  BYTEA  NOT NULL,
    cat_id BIGINT NOT NULL,
    FOREIGN KEY (cat_id) REFERENCES cats (id)
);