-- DROP TABLE IF EXISTS cats_image;
-- DROP TABLE IF EXISTS cats;

CREATE TABLE IF NOT EXISTS cats
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR     NOT NULL,
    email    VARCHAR     NOT NULL,
    password VARCHAR     NOT NULL,
    rate_cat BIGINT DEFAULT 0,
    role     VARCHAR(10) NOT NULL,
    state    VARCHAR(15) NOT NULL,
    CONSTRAINT uq_email_cat UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS cats_image
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content BYTEA  NOT NULL,
    cat_id  BIGINT NOT NULL,
    FOREIGN KEY (cat_id) REFERENCES cats (id)
);