-- DROP TABLE IF EXISTS cats_image;
-- DROP TABLE IF EXISTS cats;
-- DROP TABLE IF EXISTS persistent_logins;
-- DROP TABLE IF EXISTS token;

CREATE TABLE IF NOT EXISTS cats
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR     NOT NULL,
    email    VARCHAR     NOT NULL,
    password VARCHAR     NOT NULL,
    rate_cat BIGINT DEFAULT 0,
    role     VARCHAR(10) NOT NULL,
    state    VARCHAR(15) NOT NULL,
    token    VARCHAR(255),
    CONSTRAINT uq_email_cat UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS cats_image
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content BYTEA  NOT NULL,
    cat_id  BIGINT NOT NULL,
    FOREIGN KEY (cat_id) REFERENCES cats (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS persistent_logins
(
    username varchar(64) NOT NULL,
    series   varchar(64) NOT NULL PRIMARY KEY,
    token    varchar(64) NOT NULL,
    last_used timestamp   NOT NULL
);
